// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zouizzfomwrxfptgxkwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvdWl6emZvbXdyeGZwdGd4a3dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1NzQxMjYsImV4cCI6MjA4NjE1MDEyNn0.iA0cSNtOC1HfotBTa1-TgHXuh4Ta1zwhYWV9ydoEYJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});